/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IPolygonZkEVMBridgeInterface extends utils.Interface {
  functions: {
    "activateEmergencyState()": FunctionFragment;
    "bridgeAsset(uint32,address,uint256,address,bool,bytes)": FunctionFragment;
    "bridgeMessage(uint32,address,bool,bytes)": FunctionFragment;
    "claimAsset(bytes32[32],uint32,bytes32,bytes32,uint32,address,uint32,address,uint256,bytes)": FunctionFragment;
    "claimMessage(bytes32[32],uint32,bytes32,bytes32,uint32,address,uint32,address,uint256,bytes)": FunctionFragment;
    "deactivateEmergencyState()": FunctionFragment;
    "networkID()": FunctionFragment;
    "updateGlobalExitRoot()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "activateEmergencyState"
      | "bridgeAsset"
      | "bridgeMessage"
      | "claimAsset"
      | "claimMessage"
      | "deactivateEmergencyState"
      | "networkID"
      | "updateGlobalExitRoot"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateEmergencyState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeAsset",
    values: [BigNumberish, string, BigNumberish, string, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeMessage",
    values: [BigNumberish, string, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAsset",
    values: [
      BytesLike[],
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMessage",
    values: [
      BytesLike[],
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateEmergencyState",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "networkID", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateGlobalExitRoot",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activateEmergencyState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEmergencyState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "networkID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateGlobalExitRoot",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPolygonZkEVMBridge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPolygonZkEVMBridgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    bridgeAsset(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      token: string,
      forceUpdateGlobalExitRoot: boolean,
      permitData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    bridgeMessage(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      forceUpdateGlobalExitRoot: boolean,
      metadata: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimAsset(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originTokenAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    claimMessage(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    deactivateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    networkID(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateGlobalExitRoot(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  activateEmergencyState(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  bridgeAsset(
    destinationNetwork: BigNumberish,
    destinationAddress: string,
    amount: BigNumberish,
    token: string,
    forceUpdateGlobalExitRoot: boolean,
    permitData: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  bridgeMessage(
    destinationNetwork: BigNumberish,
    destinationAddress: string,
    forceUpdateGlobalExitRoot: boolean,
    metadata: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimAsset(
    smtProof: BytesLike[],
    index: BigNumberish,
    mainnetExitRoot: BytesLike,
    rollupExitRoot: BytesLike,
    originNetwork: BigNumberish,
    originTokenAddress: string,
    destinationNetwork: BigNumberish,
    destinationAddress: string,
    amount: BigNumberish,
    metadata: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  claimMessage(
    smtProof: BytesLike[],
    index: BigNumberish,
    mainnetExitRoot: BytesLike,
    rollupExitRoot: BytesLike,
    originNetwork: BigNumberish,
    originAddress: string,
    destinationNetwork: BigNumberish,
    destinationAddress: string,
    amount: BigNumberish,
    metadata: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  deactivateEmergencyState(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  networkID(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateGlobalExitRoot(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    activateEmergencyState(overrides?: CallOverrides): Promise<void>;

    bridgeAsset(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      token: string,
      forceUpdateGlobalExitRoot: boolean,
      permitData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgeMessage(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      forceUpdateGlobalExitRoot: boolean,
      metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    claimAsset(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originTokenAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    claimMessage(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deactivateEmergencyState(overrides?: CallOverrides): Promise<void>;

    networkID(overrides?: CallOverrides): Promise<number>;

    updateGlobalExitRoot(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    activateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    bridgeAsset(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      token: string,
      forceUpdateGlobalExitRoot: boolean,
      permitData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    bridgeMessage(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      forceUpdateGlobalExitRoot: boolean,
      metadata: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    claimAsset(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originTokenAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    claimMessage(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    deactivateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    networkID(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    updateGlobalExitRoot(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    bridgeAsset(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      token: string,
      forceUpdateGlobalExitRoot: boolean,
      permitData: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    bridgeMessage(
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      forceUpdateGlobalExitRoot: boolean,
      metadata: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimAsset(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originTokenAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    claimMessage(
      smtProof: BytesLike[],
      index: BigNumberish,
      mainnetExitRoot: BytesLike,
      rollupExitRoot: BytesLike,
      originNetwork: BigNumberish,
      originAddress: string,
      destinationNetwork: BigNumberish,
      destinationAddress: string,
      amount: BigNumberish,
      metadata: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    deactivateEmergencyState(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    networkID(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateGlobalExitRoot(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
