/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPolygonZkEVMBridge,
  IPolygonZkEVMBridgeInterface,
} from "../IPolygonZkEVMBridge";

const _abi = [
  {
    type: "function",
    name: "activateEmergencyState",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "bridgeAsset",
    inputs: [
      {
        name: "destinationNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "destinationAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
      {
        name: "forceUpdateGlobalExitRoot",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "permitData",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "bridgeMessage",
    inputs: [
      {
        name: "destinationNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "destinationAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "forceUpdateGlobalExitRoot",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "metadata",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimAsset",
    inputs: [
      {
        name: "smtProof",
        type: "bytes32[32]",
        internalType: "bytes32[32]",
      },
      {
        name: "index",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "mainnetExitRoot",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "rollupExitRoot",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "originNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "originTokenAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "destinationNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "destinationAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "metadata",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimMessage",
    inputs: [
      {
        name: "smtProof",
        type: "bytes32[32]",
        internalType: "bytes32[32]",
      },
      {
        name: "index",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "mainnetExitRoot",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "rollupExitRoot",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "originNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "originAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "destinationNetwork",
        type: "uint32",
        internalType: "uint32",
      },
      {
        name: "destinationAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "metadata",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deactivateEmergencyState",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "networkID",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateGlobalExitRoot",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "error",
    name: "AlreadyClaimed",
    inputs: [],
  },
  {
    type: "error",
    name: "AmountDoesNotMatchMsgValue",
    inputs: [],
  },
  {
    type: "error",
    name: "DestinationNetworkInvalid",
    inputs: [],
  },
  {
    type: "error",
    name: "EtherTransferFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "GlobalExitRootInvalid",
    inputs: [],
  },
  {
    type: "error",
    name: "InvalidSmtProof",
    inputs: [],
  },
  {
    type: "error",
    name: "MessageFailed",
    inputs: [],
  },
  {
    type: "error",
    name: "MsgValueNotZero",
    inputs: [],
  },
  {
    type: "error",
    name: "NotValidAmount",
    inputs: [],
  },
  {
    type: "error",
    name: "NotValidOwner",
    inputs: [],
  },
  {
    type: "error",
    name: "NotValidSignature",
    inputs: [],
  },
  {
    type: "error",
    name: "NotValidSpender",
    inputs: [],
  },
  {
    type: "error",
    name: "OnlyPolygonZkEVM",
    inputs: [],
  },
] as const;

export class IPolygonZkEVMBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IPolygonZkEVMBridgeInterface {
    return new utils.Interface(_abi) as IPolygonZkEVMBridgeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPolygonZkEVMBridge {
    return new Contract(address, _abi, signerOrProvider) as IPolygonZkEVMBridge;
  }
}
